version: '3.8'

services:
  pagopa-aca:
    container_name: pagopa-aca
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-aca-net

networks:
  pagopa-aca-net:
    driver: bridge


