version: '3.8'

services:
  pagopa-aca:
    container_name: pagopa-aca
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-aca-net
  pagopa-api-config-mock:
    container_name: pagopa-api-config-mock
    build:
      context: mock/json-server/api-config/
      dockerfile: Dockerfile.api-config-mock
    ports:
      - "8081:3000"
    networks:
      - pagopa-aca-net
  pagopa-gpd-mock:
    container_name: pagopa-gpd-mock
    build:
      context: mock/json-server/gpd/
      dockerfile: Dockerfile.gpd-mock
    ports:
      - "8082:3000"
    networks:
      - pagopa-aca-net

networks:
  pagopa-aca-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450


