apiVersion: v2
name: aca
description: Microservice that handles api for create a new debt position
type: application
version: 0.8.0
appVersion: 0.8.0
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
