microservice-chart:
  namespace: "aca"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaacaservice
    tag: "0.8.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.aca.internal.dev.platform.pagopa.it"
    path: /pagopa-aca-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "aca-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "640Mi"
      cpu: "400m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    DEFAULT_LOGGING_LEVEL: "info"
    APP_LOGGING_LEVEL: "info"
    WEB_LOGGING_LEVEL: "info"
    API_CONFIG_URI: "https://api.dev.platform.pagopa.it/apiconfig/auth/api/v1"
    API_CONFIG_READ_TIMEOUT: "10000"
    API_CONFIG_CONNECTION_TIMEOUT: "10000"
    GPD_DEBIT_POSITION_URI: "https://api.dev.platform.pagopa.it/aca/debt-positions-service/v1"
    GPD_DEBIT_POSITION_READ_TIMEOUT: "10000"
    GPD_DEBIT_POSITION_CONNECTION_TIMEOUT: "10000"
    ECS_SERVICE_NAME: "pagopa-aca-service"
    ECS_SERVICE_ENVIRONMENT: "dev"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-aca-service,deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envSecret:
    API_CONFIG_API_KEY: api-config-api-key
    GPD_DEBIT_POSITION_API_KEY: gpd-api-key
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
  keyvault:
    name: "pagopa-d-aca-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: ""
  azure:
    workloadIdentityClientId: "46ac7465-89c6-4a62-8439-9e724fe22260"
